server:
  port: 9999

spring:
  datasource:
    username: root
    password: yeqi0129
    url: jdbc:mysql:///xdb
  redis:
    port: 6379
    host: localhost



logging:
  level:
    com.yx: debug

mybatis-plus:
  mapper-locations: classpath:/sys/*.xml
  global-config:
    db-config:
      logic-delete-field: deleted #全局逻辑删除的实体字段名 最好取个跟数据库里一样的名字
      logic-not-delete-value: 0 #逻辑已删除值（默认是1）
      logic-delete-value: 1  #逻辑未删除值（默认是0）

